/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mikronis2;

import java.sql.ResultSet;
import mikronis2.dbtridy.TridaVyrobek;

/**
 *
 * @author Favak
 */
public class SkladVyrobkuFrame1 extends javax.swing.JFrame {

    private int transakceDruh;    
    private String cisloVykresu;
    private String nazevUmisteni;
    private int idUmisteni;

    public SkladVyrobkuFrame1(int transakce) {
        this.transakceDruh = transakce;
        initComponents();
        inicializaceKomponent();
        this.setVisible(true);
    }

    public SkladVyrobkuFrame1(int transakce, TridaVyrobek tv) {
        this.transakceDruh = transakce;
        this.idUmisteni = tv.getIdUmisteni();
        this.cisloVykresu = tv.getVykresCislo();
        this.nazevUmisteni = tv.getNazevUmisteni();

        initComponents();
        inicializaceKomponent();
        this.setVisible(true);
    }

    private void inicializaceKomponent() {
        if (transakceDruh == 100) {
            setTitle("Vyskladnit výrobky");
            TransakceLabel1.setText("Odebrat kusů");
        } else if (transakceDruh == 200) {
            setTitle("Naskladnit výrobky");
            TransakceLabel1.setText("Přidat kusů");
        }
        try {
            CisloVykresuTextField1.setText(cisloVykresu);
            UmisteniVeSkladuTextField1.setText(nazevUmisteni);
        } catch (Exception e) {
        }

    }

    private void provedTransakci() {
        long transakce_id = -1;
        int umisteni_id = 1;
        try {
            ResultSet transakce = PripojeniDB.dotazS("SELECT MAX(sklady_vyrobky_transakce_id) FROM logistika.sklady_vyrobky_transakce");
            while (transakce.next()) {
                transakce_id = transakce.getLong(1) + 1;
            }
            ResultSet umisteni = PripojeniDB.dotazS("SELECT sklady_vyrobky_umisteni_id "
                    + "FROM logistika.sklady_vyrobky_umisteni "
                    + "WHERE sklady_vyrobky_umisteni_nazev = '" + UmisteniVeSkladuTextField1.getText().trim() + "'");
            while (umisteni.next()) {
                umisteni_id = umisteni.getInt(1);
            }

            int pocet_mj = Integer.valueOf(PocetKusuTextField1.getText().trim()).intValue();
            int a = PripojeniDB.dotazIUD("INSERT INTO logistika.sklady_vyrobky_transakce("
                    + "sklady_vyrobky_transakce_id, "
                    + "sklady_vyrobky_transakce_sklad_id, "
                    + "sklady_vyrobky_transakce_umisteni_id, "
                    + "sklady_vyrobky_transakce_druh_id, "
                    + "sklady_vyrobky_transakce_pocet_mj, "
                    + "sklady_vyrobky_transakce_vykres_cislo) "
                    + "VALUES( " + transakce_id + ", " + 1 + ", " + umisteni_id + ", " + transakceDruh + ", " + pocet_mj + ", '"
                    + CisloVykresuTextField1.getText().trim() + "')");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TransakceLabel1 = new javax.swing.JLabel();
        CisloVykresuTextField1 = new javax.swing.JTextField();
        UmisteniVeSkladuTextField1 = new javax.swing.JTextField();
        PocetKusuTextField1 = new javax.swing.JTextField();
        jBPotvrdit = new javax.swing.JButton();
        jBZrusit = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sklad výrobků");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Číslo výkresu :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Umístění ve skladu :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel3, gridBagConstraints);

        TransakceLabel1.setText("Počet kusů :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(TransakceLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(CisloVykresuTextField1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(UmisteniVeSkladuTextField1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(PocetKusuTextField1, gridBagConstraints);

        jBPotvrdit.setText("Potvrdit");
        jBPotvrdit.setPreferredSize(new java.awt.Dimension(71, 35));
        jBPotvrdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPotvrditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 50, 5, 5);
        getContentPane().add(jBPotvrdit, gridBagConstraints);

        jBZrusit.setText("Zrušit");
        jBZrusit.setPreferredSize(new java.awt.Dimension(59, 35));
        jBZrusit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBZrusitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jBZrusit, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPotvrditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPotvrditActionPerformed
        provedTransakci();
        this.dispose();
    }//GEN-LAST:event_jBPotvrditActionPerformed

    private void jBZrusitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBZrusitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBZrusitActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CisloVykresuTextField1;
    private javax.swing.JTextField PocetKusuTextField1;
    private javax.swing.JLabel TransakceLabel1;
    private javax.swing.JTextField UmisteniVeSkladuTextField1;
    private javax.swing.JButton jBPotvrdit;
    private javax.swing.JButton jBZrusit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
