/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mikronis2;

import mikronis2.dbtridy.TridaZamestnanci1;

/**
 *
 * @author Favak
 */
public class ZamestnanecFrame1 extends javax.swing.JFrame {

     private boolean uprava = false;
    private boolean smazat = false;
    private TridaZamestnanci1 tz1;
    /**
     * Creates new form ZamestnanecFrame1
     */
    public ZamestnanecFrame1(boolean uprava) {
        tz1 = new TridaZamestnanci1();
        this.uprava = uprava;
        initComponents();
        
        this.setVisible(true);
    }
    
    public ZamestnanecFrame1(int zamestnanec_id, boolean uprava) {
        tz1 = new TridaZamestnanci1();
        tz1.selectData(zamestnanec_id);     
        this.uprava = uprava;
        initComponents();
        setData();

        this.setVisible(true);
    }
    
    private void setData() {
        jTFJmeno.setText(tz1.getJmeno());
        jTFPrijmeni.setText(tz1.getPrijmeni());
        if(!tz1.getPoznamky().isEmpty()) {
            jTAPoznamka.setText(tz1.getPoznamky());
        }            
        jCBAktivni.setSelected(tz1.isAktivni());
    }
    
    private void getData() {
        tz1.setJmeno(jTFJmeno.getText().trim());
        tz1.setPrijmeni(jTFPrijmeni.getText().trim());
        tz1.setAktivni(jCBAktivni.isSelected());
        tz1.setPoznamky(jTAPoznamka.getText().trim());
    }
        
      private void zpracovatZamestnanec() {
        if (smazat == false) {
            if (uprava == false) {
                tz1.insertData();
            } else {
                tz1.updateData();
            }
          
        } else if (smazat == true) {
            tz1.deleteData();
        }
    }  
      
      
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFJmeno = new javax.swing.JTextField();
        jTFPrijmeni = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAPoznamka = new javax.swing.JTextArea();
        jBPotvrdit = new javax.swing.JButton();
        jBZrusit = new javax.swing.JButton();
        jCBAktivni = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Údaje zaměstnanců");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Jméno");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Příjmení");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jTFJmeno, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jTFPrijmeni, gridBagConstraints);

        jLabel3.setText("Poznámka");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 100, 10);
        getContentPane().add(jLabel3, gridBagConstraints);

        jTAPoznamka.setColumns(20);
        jTAPoznamka.setRows(5);
        jScrollPane1.setViewportView(jTAPoznamka);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jBPotvrdit.setText("Potvrdit");
        jBPotvrdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPotvrditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jBPotvrdit, gridBagConstraints);

        jBZrusit.setText("Zrušit");
        jBZrusit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBZrusitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 100, 10, 100);
        getContentPane().add(jBZrusit, gridBagConstraints);

        jCBAktivni.setText("Aktivní (neaktivní zaměstnanci nebudou zobrazováni)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jCBAktivni, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPotvrditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPotvrditActionPerformed
        getData();
        zpracovatZamestnanec();
        this.dispose();
    }//GEN-LAST:event_jBPotvrditActionPerformed

    private void jBZrusitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBZrusitActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBZrusitActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBPotvrdit;
    private javax.swing.JButton jBZrusit;
    private javax.swing.JCheckBox jCBAktivni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTAPoznamka;
    private javax.swing.JTextField jTFJmeno;
    private javax.swing.JTextField jTFPrijmeni;
    // End of variables declaration//GEN-END:variables
}
